<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class FrontendSetting extends Model
{
    protected $attributes = [
        'site_enabled' => true,
        'home_enabled' => true,
        'brand_name' => 'Cerape',
        'logo_path' => null,
        'hero_title' => 'Como funciona',
        'hero_subtitle' => 'Conteúdo editável pelo painel /frontend.',
        'hero_cta_label' => 'Agendar uma conversa',
        'hero_secondary_cta_label' => 'Conhecer a jornada',
        'about_title' => 'Sobre a CERAPE',
        'about_paragraph_one' => 'A CERAPE é uma casa de recuperação dedicada a oferecer acolhimento, tratamento e um novo começo para quem enfrenta a dependência química.',
        'about_paragraph_two' => 'Acreditamos que a recuperação acontece em comunidade: por isso trabalhamos junto às famílias, com transparência e respeito ao tempo de cada pessoa, do primeiro dia até a reinserção social.',
        'about_video_url' => null,
        'about_video_width' => 560,
        'about_video_height' => 315,
        'journey_eyebrow' => 'Como funciona',
        'journey_title' => 'Uma jornada em quatro etapas',
        'journey_description' => 'Cada fase tem objetivos claros, sempre com acompanhamento próximo da família e da equipe técnica.',
        'journey_empty_title_one' => 'Acolhimento',
        'journey_empty_title_two' => 'Estabilização',
        'journey_empty_title_three' => 'Fortalecimento',
        'journey_empty_title_four' => 'Reinserção',
        'journey_empty_description' => 'Cadastre os pilares no painel /frontend.',
        'team_eyebrow' => 'Equipe',
        'team_title' => 'Quem cuida de você',
        'team_description' => 'Uma equipe multiprofissional acompanha cada etapa do tratamento, em conjunto e com plano individual para cada residente.',
        'team_empty_message' => 'Cadastre a equipe no painel /frontend.',
        'gallery_eyebrow' => 'Nosso espaço',
        'gallery_title' => 'Galeria',
        'gallery_description' => 'Um ambiente pensado para acolher: áreas comuns, quartos, jardim e espaços terapêuticos.',
        'gallery_empty_message' => 'Cadastre as categorias da galeria no painel /frontend.',
        'gallery_all_label' => 'Todos',
        'blog_eyebrow' => 'Conteúdo',
        'blog_title' => 'Blog',
        'blog_description' => 'Artigos para famílias e pacientes sobre recuperação, saúde mental e reconstrução de vínculos.',
        'blog_empty_message' => 'Cadastre até 5 cards do blog no painel /frontend.',
        'contact_section_eyebrow' => 'Atendimento confidencial',
        'contact_section_title' => 'Vamos conversar',
        'contact_section_description' => 'Toda mensagem é tratada com sigilo. Nossa equipe responde em até 24h.',
        'contact_whatsapp_title' => 'Fale com a nossa equipe agora pelo WhatsApp.',
        'contact_whatsapp_footer' => 'Atendimento 24h',
        'menu_label_about' => 'Quem somos',
        'menu_label_home' => 'Iniciar',
        'menu_label_pillars' => 'Pilares',
        'menu_label_team' => 'Equipe',
        'menu_label_gallery' => 'Galeria',
        'menu_label_blog' => 'Blog',
        'menu_label_contact' => 'Contato',
        'header_primary_color' => '#0f172a',
        'header_secondary_color' => '#155e75',
        'footer_primary_color' => '#111827',
        'footer_secondary_color' => '#0f766e',
        'font_color' => '#e5e7eb',
        'accent_color' => '#38bdf8',
        'clinic_name' => 'Clínica CERAPE',
        'clinic_description' => 'Veja abaixo onde fica a clínica de recuperação e como chegar.',
        'clinic_contact_title' => 'Informações',
        'clinic_contact_name' => 'Clínica CERAPE',
        'clinic_contact_address_label' => 'Endereço',
        'clinic_contact_address_line' => 'Rua das Acácias, 120 — Bairro Jardim, São Paulo/SP',
        'clinic_contact_city_label' => 'Cidade',
        'clinic_contact_city_line' => 'São Paulo',
        'clinic_contact_state_label' => 'Estado',
        'clinic_contact_state_line' => 'SP',
        'clinic_contact_zip_label' => 'CEP',
        'clinic_contact_zip_line' => '00000-000',
        'clinic_contact_phone_label' => 'Telefone',
        'clinic_contact_phone_line' => '(11) 0000-0000',
        'clinic_contact_email_label' => 'E-mail',
        'clinic_contact_email_line' => 'contato@cerape.com',
        'contact_eyebrow' => 'Atendimento confidencial',
        'contact_title' => 'Vamos conversar',
        'contact_description' => 'Toda mensagem é tratada com sigilo. Nossa equipe responde em até 24h.',
        'contact_phone_label' => 'Telefone',
        'contact_phone_line' => '(11) 0000-0000 · WhatsApp 24h',
        'contact_whatsapp_cta_label' => 'Conversar no WhatsApp',
        'contact_address_label' => 'Endereço',
        'contact_address_line' => 'Rua das Acácias, 120 — Bairro Jardim, São Paulo/SP',
        'contact_email_label' => 'E-mail',
        'contact_email_line' => 'contato@cerape.com',
        'contact_form_name_placeholder' => 'Seu nome',
        'contact_form_phone_placeholder' => '(00) 00000-0000',
        'contact_form_email_placeholder' => 'seu@email.com',
        'contact_form_message_placeholder' => 'Como podemos ajudar?',
    ];

    protected $fillable = [
        'site_enabled',
        'home_enabled',
        'brand_name',
        'logo_path',
        'hero_title',
        'hero_subtitle',
        'hero_cta_label',
        'hero_secondary_cta_label',
        'about_title',
        'about_paragraph_one',
        'about_paragraph_two',
        'about_image_path',
        'about_video_url',
        'about_video_width',
        'about_video_height',
        'journey_eyebrow',
        'journey_title',
        'journey_description',
        'journey_empty_title_one',
        'journey_empty_title_two',
        'journey_empty_title_three',
        'journey_empty_title_four',
        'journey_empty_description',
        'team_eyebrow',
        'team_title',
        'team_description',
        'team_empty_message',
        'gallery_eyebrow',
        'gallery_title',
        'gallery_description',
        'gallery_empty_message',
        'gallery_all_label',
        'blog_eyebrow',
        'blog_title',
        'blog_description',
        'blog_empty_message',
        'contact_section_eyebrow',
        'contact_section_title',
        'contact_section_description',
        'contact_whatsapp_title',
        'contact_whatsapp_footer',
        'menu_label_about',
        'menu_label_home',
        'menu_label_pillars',
        'menu_label_team',
        'menu_label_gallery',
        'menu_label_blog',
        'menu_label_contact',
        'header_primary_color',
        'header_secondary_color',
        'footer_primary_color',
        'footer_secondary_color',
        'font_color',
        'accent_color',
        'clinic_name',
        'clinic_address',
        'clinic_city',
        'clinic_state',
        'clinic_zip_code',
        'clinic_google_maps_embed',
        'clinic_maps_link',
        'clinic_description',
        'clinic_contact_title',
        'clinic_contact_name',
        'clinic_contact_address_label',
        'clinic_contact_address_line',
        'clinic_contact_city_label',
        'clinic_contact_city_line',
        'clinic_contact_state_label',
        'clinic_contact_state_line',
        'clinic_contact_zip_label',
        'clinic_contact_zip_line',
        'clinic_contact_phone_label',
        'clinic_contact_phone_line',
        'clinic_contact_email_label',
        'clinic_contact_email_line',
        'whatsapp_number',
        'whatsapp_message',
        'site_email',
        'contact_eyebrow',
        'contact_title',
        'contact_description',
        'contact_phone_label',
        'contact_phone_line',
        'contact_whatsapp_cta_label',
        'contact_address_label',
        'contact_address_line',
        'contact_email_label',
        'contact_email_line',
        'contact_form_name_placeholder',
        'contact_form_phone_placeholder',
        'contact_form_email_placeholder',
        'contact_form_message_placeholder',
    ];

    protected $casts = [
        'site_enabled' => 'boolean',
        'home_enabled' => 'boolean',
    ];
}
